### ISSUE TITLE
add image for twitter

### ISSUE THREAD

**Issue by M0nica** [react-ladies/React-Ladies#27]
Add meta image that will display on twitter card https://cards-dev.twitter.com/validator

Currently no image displays :( 

<img width="1116" alt="Screen Shot 2019-05-21 at 2 07 56 PM" src="https://user-images.githubusercontent.com/6998954/58119829-ea40b000-7bd1-11e9-89b6-07bfb7580ee4.png">

The below image can be used:
![image](https://user-images.githubusercontent.com/6998954/58119974-3986e080-7bd2-11e9-87aa-a703fb70f525.png)

**Comment by thefifthisa** [comment]
Hi, I'd like to work on this! This is what I get on the card validator though 😕 Will dig into the issue.

<img width="1023" alt="Screen Shot 2019-10-13 at 11 32 47 AM" src="https://user-images.githubusercontent.com/30595954/66718040-5a341a80-edad-11e9-8987-22fb47c84602.png">

**Comment by M0nica** [comment]
This was resolved in https://github.com/react-ladies/React-Ladies/pull/71
