### ISSUE TITLE
Add SEO information

### ISSUE THREAD

**Issue by M0nica** [react-ladies/React-Ladies#40]
Add SEO information to the site

Description: We're a community of women and non-binary ReactJS enthusiasts in New York City (and beyond) 

Preview image should be the purple React logo

**Comment by teknotica** [comment]
Hi 👋 - I noticed there's already some meta tags in the site. Is this "issue" an update for the current data?

**Comment by M0nica** [comment]
@teknotica I think the main update is to have the image preview update to reflect the purple React logo

**Comment by M0nica** [comment]
I've addressed this in the `beta` branch.
