### ISSUE TITLE
Improve Error Messaging

### ISSUE THREAD

**Issue by M0nica** [react-ladies/React-Ladies#64]
<p>Currently, if the registration function returns an error that information is not displayed to the end-user. </p>
<p>Given:<br>
I'm a user who submits an RSVP</p>
<p>When:<br>
There's an error RSVP-ing me (i.e., saving the data to Airtable)</p>
<p>Then:<br>
Render a message on the front end saying something went wrong and prompting me to submit the form again</p>
<p>There currently isn't a loading state upon submitting so that may be 
something that can be tackled while adding better error messaging.</p>

Note: This work should fork off of the `beta` branch.

**Comment by afif1400** [comment]
Can I work on this?

**Comment by M0nica** [comment]
@afif1400 Yes, you can work on this although https://github.com/react-ladies/React-Ladies/issues/67 is higher priority. Since you’re interested in both can you work on #67 first and then if this particular issue  is still unassigned pick it up?

**Comment by M0nica** [comment]
@afif1400 this is available to be worked on. Are you more interested in working on this issue or https://github.com/react-ladies/React-Ladies/issues/67?

**Comment by afif1400** [comment]
I have submitted a PR that resolves issue #67, I can take up this one.

**Comment by M0nica** [comment]
Okay, that sounds good @afif1400!
