### ISSUE TITLE
bug: characters omitted from airtable

### ISSUE THREAD

**Issue by M0nica** [react-ladies/React-Ladies#67]
There's currently a defect where if you input an e-mail like monica+test@gmail.com the + is being omitted in Airtable. The way we are sending data to airtable should be updated to ensure we do not lose special characters from email addresses

Note: This work should fork off of the `beta` branch.

**Comment by afif1400** [comment]
Can I work on this?

**Comment by M0nica** [comment]
Yes @afif1400 this is a high priority issue! If you’re able to work on this soon that would be great. If not, let me know as I may pick it up. Thank you for your interest in contributing.

**Comment by M0nica** [comment]
I did put in a hot fix to prevent users from submitting e-mail addresses with + signs so when this encoding issue is resolved then https://github.com/react-ladies/React-Ladies/pull/70 should be reverted so that folks can continue submitting e-mail addresses with plus signs.

**Comment by afif1400** [comment]
> There's currently a defect where if you input an e-mail like [monica+test@gmail.com](mailto:monica+test@gmail.com) the + is being omitted in Airtable. The way we are sending data to airtable should be updated to ensure we do not lose special characters from email addresses

I used the airtable API to send an email address from the register function it **does not** omit the  **+** character.

+ API request URL
![Screenshot from 2021-05-28 17-18-42](https://user-images.githubusercontent.com/51887071/119979667-e3c34b00-bfd8-11eb-9737-90c14eb8692d.png)

+ table content
![Screenshot from 2021-05-28 17-18-17](https://user-images.githubusercontent.com/51887071/119979783-035a7380-bfd9-11eb-8407-202f7cd0a3a6.png)

please, let me know if this is was the bug or from the client-side because the function logic is correct.

**Comment by M0nica** [comment]
> > There's currently a defect where if you input an e-mail like [monica+test@gmail.com](mailto:monica+test@gmail.com) the + is being omitted in Airtable. The way we are sending data to airtable should be updated to ensure we do not lose special characters from email addresses
> 
> I used the airtable API to send an email address from the register function it **does not** omit the **+** character.
> 
> * API request URL
>   ![Screenshot from 2021-05-28 17-18-42](https://user-images.githubusercontent.com/51887071/119979667-e3c34b00-bfd8-11eb-9737-90c14eb8692d.png)
> * table content
>   ![Screenshot from 2021-05-28 17-18-17](https://user-images.githubusercontent.com/51887071/119979783-035a7380-bfd9-11eb-8407-202f7cd0a3a6.png)
> 
> please, let me know if this is was the bug or from the client-side because the function logic is correct.

@afif1400 Can you try to reproduce using the same encodeURI function that the client side is using to construct the API URL? Based on what you’re seeing it seems that the the issue may be related to how the client side is passing in the data to the API. https://github.com/react-ladies/React-Ladies/blob/31d7febd2c80a3ee3edfbd8aa87803e5dc7ba901/src/components/Info/Form.js#L18

Note:  Depending on your version of the branch you may need to update the RegExp for email validation to allow you to submit a form with a plus sign before the @ symbol.

**Comment by afif1400** [comment]
> > > There's currently a defect where if you input an e-mail like [monica+test@gmail.com](mailto:monica+test@gmail.com) the + is being omitted in Airtable. The way we are sending data to airtable should be updated to ensure we do not lose special characters from email addresses
> > 
> > 
> > I used the airtable API to send an email address from the register function it **does not** omit the **+** character.
> > 
> > * API request URL
> >   ![Screenshot from 2021-05-28 17-18-42](https://user-images.githubusercontent.com/51887071/119979667-e3c34b00-bfd8-11eb-9737-90c14eb8692d.png)
> > * table content
> >   ![Screenshot from 2021-05-28 17-18-17](https://user-images.githubusercontent.com/51887071/119979783-035a7380-bfd9-11eb-8407-202f7cd0a3a6.png)
> > 
> > please, let me know if this is was the bug or from the client-side because the function logic is correct.
> 
> @afif1400 Can you try to reproduce using the same encodeURI function that the client side is using to construct the API URL? Based on what you’re seeing it seems that the the issue may be related to how the client side is passing in the data to the API.
> 
> https://github.com/react-ladies/React-Ladies/blob/31d7febd2c80a3ee3edfbd8aa87803e5dc7ba901/src/components/Info/Form.js#L18
> 
> Note: Depending on your version of the branch you may need to update the RegExp for email validation to allow you to submit a form with a plus sign before the @ symbol.

Yeah... I'll try from the client side.

**Comment by M0nica** [comment]
This issue appears to be resolved in https://github.com/react-ladies/React-Ladies/pull/74 so I will close out this issue.
